version: '3.8'

services:
  # 1. Database: PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shop_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Caching: Redis
  redis-cache:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6379:6379"

  # 3. Application: SpringBoot
  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - redis-cache
    environment:
      # Connect to the DB by using the service name 'postgres-db'
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/shop_app
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      # Connect to Redis by using the name 'redis-cache'
      SPRING_DATA_REDIS_HOST: redis-cache
      SPRING_DATA_REDIS_PORT: 6379
      # Automatically update the DB
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # CORS
      ALLOWED_ORIGINS: http://localhost:3000
      FILE_UPLOAD_DIR: /var/lib/data/uploads

      # VNPay
      VNPAY_RETURN_URL: http://localhost:3000/vnpay_payment_channel
      #
      SAME_SITE: Lax

volumes:
  postgres_data: